//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableStatu
    {
        public string tableName { get; set; }
        public System.DateTime checkDate { get; set; }
        public Nullable<int> numberOfRows { get; set; }
        public Nullable<double> rateCheckValue { get; set; }
        public Nullable<int> fastGrowth { get; set; }
    }
}
